apiVersion: apps/v1
kind: Deployment

metadata:
  name: kubernetes-dashboard

spec:
  replicas: 2

  selector:
    matchLabels:
      app: kubernetes-dashboard

  template:
    metadata:
      labels:
        app: kubernetes-dashboard

    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: kubernetes-dashboard
          image: suchit10/kubernetes-github-actions:v1
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true

            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          ports:
            - containerPort: 5000